apiVersion: apps/v1
kind: Deployment
metadata:
  name: anomaly-detector
  labels:
    app: anomaly-detector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anomaly-detector
  template:
    metadata:
      labels:
        app: anomaly-detector
    spec:
      containers:
        - name: anomaly-detector
          image: siddhesh2263/anomaly-detector:v1
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service:9092"