apiVersion: apps/v1
kind: Deployment
metadata:
  name: map-render
  labels:
    app: map-render
spec:
  replicas: 1
  selector:
    matchLabels:
      app: map-render
  template:
    metadata:
      labels:
        app: map-render
    spec:
      containers:
        - name: map-render
          image: siddhesh2263/map-render:v3
          ports:
            - containerPort: 5000
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: map-render-service
spec:
  type: NodePort
  selector:
    app: map-render
  ports:
    - protocol: TCP
      port: 5000        # Internal port Flask is listening on
      targetPort: 5000  # Matches containerPort
      nodePort: 30070   # Access externally via <K3S_NODE_IP>:30070